server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.104:5432/dynamicSearch
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
  jpa:
    defer-datasource-initialization: true
    show-sql: true

